# Generated by Django 4.0.3 on 2023-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fawry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('money_borrowed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_payed_back', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed_date', models.DateField()),
                ('restore_date', models.DateField()),
            ],
        ),
    ]
