# Generated by Django 4.0.3 on 2023-06-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fawry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='fawry',
            name='payed_date',
        ),
        migrations.RemoveField(
            model_name='fawry',
            name='restore_date',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fawry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fawry.fawry')),
            ],
        ),
    ]
