# Generated by Django 4.0.3 on 2023-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawry', '0002_user_remove_fawry_payed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fawry',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
