# Generated by Django 4.0.3 on 2023-06-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawry', '0003_fawry_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='fawry',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
