# Generated by Django 4.0.3 on 2023-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawry', '0004_fawry_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
