# Generated by Django 4.0.3 on 2023-06-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawry', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fawry',
            name='profit',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10),
        ),
    ]
