# Generated by Django 4.0.3 on 2023-06-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawry', '0007_alter_fawry_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fawry',
            name='profit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.CharField(choices=[('كاش', 'كاش'), ('فوري', 'فوري')], default=0, max_length=10),
        ),
    ]
