# Generated by Django 4.0.3 on 2023-06-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fawry', '0008_remove_fawry_profit_transaction_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.CharField(choices=[('كاش', 'كاش'), ('فوري', 'فوري')], default=1, max_length=10),
        ),
    ]
